export const ProductsData = [
  {
    id: 1,
    category: "shirts",
    name: "Classic White Shirt",
    description: "A timeless white shirt perfect for formal or casual wear.",
    price: 25.99,
    colors: ["White", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 10,
    image: 'https://images.pexels.com/photos/991509/pexels-photo-991509.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 2,
    category: "shirts",
    name: "Plaid Casual Shirt",
    description: "A trendy plaid shirt suitable for casual outings.",
    price: 29.99,
    colors: ["Red", "Green"],
    sizes: ["M", "L", "XL"],
    stock: 8,
    image: "https://images.unsplash.com/photo-1485145782098-4f5fd605a66b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2hpcnR8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 3,
    category: "t-shirts",
    name: "Graphic Tee",
    description: "Comfortable graphic t-shirt with a unique design.",
    price: 19.99,
    colors: ["Black", "White"],
    sizes: ["S", "M", "L"],
    stock: 15,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hpcnR8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 4,
    category: "t-shirts",
    name: "Plain Cotton T-Shirt",
    description: "Simple and breathable cotton t-shirt for daily wear.",
    price: 15.99,
    colors: ["White", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    stock: 20,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hpcnR8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 5,
    category: "jeans",
    name: "Skinny Fit Jeans",
    description: "Skinny fit jeans that hug your legs for a modern look.",
    price: 39.99,
    colors: ["Blue", "Black"],
    sizes: ["28", "30", "32", "34"],
    stock: 12,
    image: 'https://images.pexels.com/photos/10599447/pexels-photo-10599447.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 6,
    category: "jeans",
    name: "Relaxed Fit Jeans",
    description: "Relaxed fit jeans for a comfortable everyday style.",
    price: 34.99,
    colors: ["Dark Blue", "Light Blue"],
    sizes: ["30", "32", "34", "36"],
    stock: 18,
    image: 'https://images.pexels.com/photos/7787186/pexels-photo-7787186.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 7,
    category: "hoodies",
    name: "Classic Hoodie",
    description: "A cozy hoodie with a drawstring and kangaroo pocket.",
    price: 45.99,
    colors: ["Black", "Gray", "Red"],
    sizes: ["S", "M", "L", "XL"],
    stock: 10,
    image: "https://images.unsplash.com/photo-1718912502515-d8210f247807?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8aG9vZGllJTIwYW5kJTIwaGF0fGVufDB8fDB8fHww",
  },
  {
    id: 8,
    category: "hoodies",
    name: "Zip-Up Hoodie",
    description: "Versatile zip-up hoodie for layering in cooler weather.",
    price: 49.99,
    colors: ["Navy", "Green"],
    sizes: ["S", "M", "L"],
    stock: 8,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 9,
    category: "shorts",
    name: "Cotton Shorts",
    description: "Lightweight cotton shorts for warm weather.",
    price: 19.99,
    colors: ["Khaki", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
    image: 'https://images.pexels.com/photos/2532090/pexels-photo-2532090.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 10,
    category: "shorts",
    name: "Sports Shorts",
    description: "Comfortable shorts for workouts and casual activities.",
    price: 21.99,
    colors: ["Black", "Navy"],
    sizes: ["M", "L", "XL"],
    stock: 30,
    image: "https://images.unsplash.com/photo-1591258370467-f1ca1d70ea8f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hvcnRzfGVufDB8fDB8fHww",
  },
  {
    id: 11,
    category: "shirts",
    name: "Denim Shirt",
    description: "A rugged denim shirt for a casual yet stylish look.",
    price: 34.99,
    colors: ["Blue", "Dark Blue"],
    sizes: ["M", "L", "XL"],
    stock: 14,
    image: "https://images.unsplash.com/photo-1617171594207-430a01a9da3f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGhvb2RpZSUyMGFuZCUyMGhhdHxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 12,
    category: "t-shirts",
    name: "V-Neck T-Shirt",
    description: "Soft and breathable V-neck t-shirt for casual wear.",
    price: 17.99,
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 19,
    image: "https://images.unsplash.com/photo-1516203690324-fa211a7c84f2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvb2RpZSUyMGFuZCUyMGhhdHxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 13,
    category: "jeans",
    name: "Bootcut Jeans",
    description: "Bootcut jeans for a retro and stylish vibe.",
    price: 42.99,
    colors: ["Blue", "Black"],
    sizes: ["28", "30", "32", "34"],
    stock: 10,
    image: 'https://images.pexels.com/photos/9125752/pexels-photo-9125752.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 14,
    category: "hoodies",
    name: "Oversized Hoodie",
    description: "A comfortable oversized hoodie for a relaxed fit.",
    price: 54.99,
    colors: ["Beige", "Black"],
    sizes: ["M", "L", "XL"],
    stock: 12,
    image: "https://images.unsplash.com/photo-1569240192190-e37f8b0010be?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvb2RpZSUyMGFuZCUyMGhhdHxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 15,
    category: "shorts",
    name: "Denim Shorts",
    description: "Stylish denim shorts for a summer wardrobe essential.",
    price: 25.99,
    colors: ["Blue", "Black"],
    sizes: ["M", "L", "XL"],
    stock: 22,
    image: 'https://images.pexels.com/photos/2383139/pexels-photo-2383139.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 16,
    category: "t-shirts",
    name: "Striped T-Shirt",
    description: "Trendy striped t-shirt to elevate your casual outfits.",
    price: 19.99,
    colors: ["Black/White", "Blue/White"],
    sizes: ["S", "M", "L"],
    stock: 15,
    image: "https://images.pexels.com/photos/19129582/pexels-photo-19129582/free-photo-of-woman-sitting-on-wall-and-posing-with-hand-on-chin.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 17,
    category: "shirts",
    name: "Oxford Shirt",
    description: "A premium oxford shirt suitable for both office and parties.",
    price: 49.99,
    colors: ["White", "Sky Blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 18,
    image: 'https://images.pexels.com/photos/29441737/pexels-photo-29441737/free-photo-of-casual-pose-in-ho-chi-minh-city-temple-alleyway.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 18,
    name: "Classic White Shirt",
    description: "A timeless white shirt perfect for formal occasions.",
    category: "shirts",
    price: 25.99,
    colors: ["white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
    image: "https://images.pexels.com/photos/12836129/pexels-photo-12836129.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 19,
    name: "Casual T-Shirt",
    description: "Comfortable and casual t-shirt for everyday wear.",
    category: "t-shirts",
    price: 15.99,
    colors: ["black", "grey", "white"],
    sizes: ["S", "M", "L"],
    stock: 100,
    image: "https://images.pexels.com/photos/8993497/pexels-photo-8993497.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 20,
    name: "Slim Fit Jeans",
    description: "Stylish slim-fit jeans with a modern design.",
    category: "jeans",
    price: 49.99,
    colors: ["blue", "black"],
    sizes: ["30", "32", "34", "36"],
    stock: 70,
    image: "https://images.pexels.com/photos/15420245/pexels-photo-15420245/free-photo-of-man-wearing-jean-jacket-and-sunglasses-standing-by-wall-with-blue-window-shutters.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 21,
    name: "Comfortable Hoodie",
    description: "Cozy hoodie for chilly weather.",
    category: "hoodies",
    price: 39.99,
    colors: ["red", "black", "grey"],
    sizes: ["M", "L", "XL"],
    stock: 30,
    image: "https://images.pexels.com/photos/6311540/pexels-photo-6311540.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 22,
    name: "Cotton Shorts",
    description: "Breathable shorts perfect for summer days.",
    category: "shorts",
    price: 20.99,
    colors: ["blue", "khaki", "black"],
    sizes: ["S", "M", "L"],
    stock: 40,
    image: "https://images.pexels.com/photos/3622624/pexels-photo-3622624.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 23,
    name: "Striped Polo Shirt",
    description: "Elegant striped polo shirt for casual outings.",
    category: "shirts",
    price: 29.99,
    colors: ["green", "blue", "white"],
    sizes: ["S", "M", "L"],
    stock: 60,
    image: 'https://images.pexels.com/photos/965324/pexels-photo-965324.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 24,
    name: "Graphic T-Shirt",
    description: "Trendy t-shirt with cool graphics.",
    category: "t-shirts",
    price: 19.99,
    colors: ["white", "black"],
    sizes: ["M", "L", "XL"],
    stock: 90,
    image: "https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 25,
    name: "Relaxed Fit Jeans",
    description: "Relaxed-fit jeans for maximum comfort.",
    category: "jeans",
    price: 54.99,
    colors: ["blue", "grey"],
    sizes: ["30", "32", "34", "36", "38"],
    stock: 80,
    image: "https://images.pexels.com/photos/2343661/pexels-photo-2343661.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 26,
    name: "Zip-Up Hoodie",
    description: "Stylish zip-up hoodie for layering.",
    category: "hoodies",
    price: 42.99,
    colors: ["navy", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    stock: 35,
    image: "https://images.pexels.com/photos/29463956/pexels-photo-29463956/free-photo-of-man-in-black-outfit-by-seaside-promenade.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 27,
    name: "Athletic Shorts",
    description: "Perfect shorts for gym and outdoor activities.",
    category: "shorts",
    price: 18.99,
    colors: ["black", "grey"],
    sizes: ["S", "M", "L"],
    stock: 50,
    image: "https://images.pexels.com/photos/2532090/pexels-photo-2532090.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 28,
    name: "Denim Jacket",
    description: "Classic denim jacket with a modern twist.",
    category: "jackets",
    price: 59.99,
    colors: ["blue", "black"],
    sizes: ["M", "L", "XL"],
    stock: 20,
    image: "https://images.pexels.com/photos/29464999/pexels-photo-29464999/free-photo-of-smiling-young-man-sitting-in-urban-setting.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 29,
    name: "Plaid Shirt",
    description: "Casual plaid shirt for a laid-back style.",
    category: "shirts",
    price: 24.99,
    colors: ["red", "green"],
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
    image: "https://images.pexels.com/photos/29466467/pexels-photo-29466467/free-photo-of-fashionable-woman-posing-in-trendy-outfit-indoors.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 30,
    name: "Vintage Hoodie",
    description: "Retro hoodie with a vintage design.",
    category: "hoodies",
    price: 45.99,
    colors: ["yellow", "green"],
    sizes: ["M", "L"],
    stock: 25,
    image: "https://images.pexels.com/photos/1035679/pexels-photo-1035679.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 31,
    name: "Cargo Shorts",
    description: "Practical cargo shorts with extra pockets.",
    category: "shorts",
    price: 22.99,
    colors: ["khaki", "green"],
    sizes: ["M", "L"],
    stock: 30,
    image: "https://images.pexels.com/photos/29471248/pexels-photo-29471248/free-photo-of-traveler-with-camera-at-busy-train-station.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 32,
    name: "Classic White Shirt",
    description: "A timeless white shirt for all occasions.",
    price: 25.99,
    category: "shirts",
    colors: ["white"],
    sizes: ["S", "M", "L", "XL"],
    stock: 20,
    image: "https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 33,
    name: "Casual Blue Jeans",
    description: "Comfortable blue jeans for everyday wear.",
    price: 45.99,
    category: "jeans",
    colors: ["blue"],
    sizes: ["28", "30", "32", "34", "36"],
    stock: 15,
    image: "https://images.pexels.com/photos/398078/pexels-photo-398078.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 34,
    name: "Graphic T-Shirt",
    description: "Trendy graphic T-shirt with a vibrant design.",
    price: 19.99,
    category: "t-shirts",
    colors: ["black", "white"],
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
    image: "https://images.pexels.com/photos/1018911/pexels-photo-1018911.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 35,
    name: "Fleece Hoodie",
    description: "Warm and cozy fleece hoodie for chilly days.",
    price: 39.99,
    category: "hoodies",
    colors: ["gray", "black"],
    sizes: ["M", "L", "XL"],
    stock: 10,
    image: "https://images.pexels.com/photos/47037/man-male-boy-the-young-man-47037.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 36,
    name: "Cotton Shorts",
    description: "Lightweight cotton shorts for summer.",
    price: 15.99,
    category: "shorts",
    colors: ["beige", "khaki"],
    sizes: ["S", "M", "L", "XL"],
    stock: 30,
    image: "https://images.pexels.com/photos/1963233/pexels-photo-1963233.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 37,
    name: "Striped Polo Shirt",
    description: "Stylish striped polo shirt with a classic fit.",
    price: 29.99,
    category: "shirts",
    colors: ["blue", "red", "white"],
    sizes: ["M", "L", "XL"],
    stock: 12,
    image: "https://images.pexels.com/photos/2635315/pexels-photo-2635315.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 38,
    name: "Ripped Skinny Jeans",
    description: "Trendy ripped skinny jeans for a modern look.",
    price: 49.99,
    category: "jeans",
    colors: ["blue", "black"],
    sizes: ["28", "30", "32", "34"],
    stock: 18,
    image: "https://images.pexels.com/photos/2068349/pexels-photo-2068349.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 39,
    name: "Plain Crew Neck T-Shirt",
    description: "Simple crew neck T-shirt in solid colors.",
    price: 14.99,
    category: "t-shirts",
    colors: ["white", "gray", "navy"],
    sizes: ["S", "M", "L", "XL"],
    stock: 40,
    image: "https://images.pexels.com/photos/1887975/pexels-photo-1887975.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 40,
    name: "Oversized Hoodie",
    description: "Comfy oversized hoodie with a relaxed fit.",
    price: 34.99,
    category: "hoodies",
    colors: ["black", "brown"],
    sizes: ["L", "XL", "XXL"],
    stock: 22,
    image: "https://images.pexels.com/photos/1906157/pexels-photo-1906157.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 41,
    name: "Sport Shorts",
    description: "Quick-dry shorts perfect for workouts.",
    price: 18.99,
    category: "shorts",
    colors: ["black", "gray"],
    sizes: ["S", "M", "L"],
    stock: 25,
    image: "https://images.pexels.com/photos/3610826/pexels-photo-3610826.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 42,
    name: "Denim Jacket",
    description: "Classic denim jacket with a modern twist.",
    price: 59.99,
    category: "shirts",
    colors: ["blue", "black"],
    sizes: ["M", "L", "XL"],
    stock: 14,
    image: "https://images.pexels.com/photos/10821628/pexels-photo-10821628.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 43,
    name: "Slim Fit Jeans",
    description: "Slim fit jeans for a sleek and stylish look.",
    price: 44.99,
    category: "jeans",
    colors: ["dark blue", "gray"],
    sizes: ["30", "32", "34", "36"],
    stock: 20,
    image: "https://images.pexels.com/photos/4505458/pexels-photo-4505458.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 44,
    name: "Printed T-Shirt",
    description: "Fun printed T-shirt with unique designs.",
    price: 22.99,
    category: "t-shirts",
    colors: ["white", "yellow"],
    sizes: ["S", "M", "L"],
    stock: 35,
    image: "https://images.pexels.com/photos/1188748/pexels-photo-1188748.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 45,
    name: "Zipper Hoodie",
    description: "Casual hoodie with a convenient zipper closure.",
    price: 32.99,
    category: "hoodies",
    colors: ["blue", "red"],
    sizes: ["M", "L", "XL"],
    stock: 18,
    image: "https://images.pexels.com/photos/2787351/pexels-photo-2787351.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 46,
    name: "Cargo Shorts",
    description: "Durable cargo shorts with multiple pockets.",
    price: 24.99,
    category: "shorts",
    colors: ["khaki", "green"],
    sizes: ["S", "M", "L"],
    stock: 28,
    image: "https://images.pexels.com/photos/2383139/pexels-photo-2383139.jpeg?auto=compress&cs=tinysrgb&w=600",
  },

  {
    id: 47,
    category: "shirts",
    name: "Denim Shirt",
    description: "A stylish denim shirt for a rugged look.",
    price: 32.99,
    colors: ["Blue", "Light Blue"],
    sizes: ["S", "M", "L"],
    stock: 15,
    image: "https://images.pexels.com/photos/2421356/pexels-photo-2421356.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 48,
    category: "shirts",
    name: "Linen Shirt",
    description: "Breathable linen shirt for hot days.",
    price: 27.99,
    colors: ["Beige", "White"],
    sizes: ["S", "M", "L", "XL"],
    stock: 20,
    image: "https://images.pexels.com/photos/29367708/pexels-photo-29367708/free-photo-of-fashionable-woman-posing-near-patek-philippe-sign.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 49,
    category: "pants",
    name: "Chino Pants",
    description: "Comfortable and stylish chino pants.",
    price: 39.99,
    colors: ["Khaki", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
    image: "https://images.pexels.com/photos/11940641/pexels-photo-11940641.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 50,
    category: "jackets",
    name: "Leather Jacket",
    description: "Classic leather jacket for a bold style.",
    price: 120.99,
    colors: ["Black", "Brown"],
    sizes: ["M", "L", "XL"],
    stock: 10,
    image: "https://images.pexels.com/photos/1381565/pexels-photo-1381565.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 51,
    category: "shirts",
    name: "Graphic Tee",
    description: "Casual T-shirt with unique graphic prints.",
    price: 19.99,
    colors: ["White", "Black", "Grey"],
    sizes: ["S", "M", "L"],
    stock: 30,
    image: "https://images.pexels.com/photos/27893233/pexels-photo-27893233/free-photo-of-woman-in-shirt-photographing-with-digital-camera.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 52,
    category: "accessories",
    name: "Baseball Cap",
    description: "Adjustable cap for casual outings.",
    price: 14.99,
    colors: ["Black", "Blue", "Red"],
    sizes: ["One Size"],
    stock: 40,
    image: "https://images.pexels.com/photos/17243499/pexels-photo-17243499/free-photo-of-a-woman-leaning-against-a-wall-wearing-a-crop-top.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 53,
    category: "shoes",
    name: "Running Shoes",
    description: "Lightweight running shoes for active wear.",
    price: 59.99,
    colors: ["White", "Black"],
    sizes: ["8", "9", "10", "11"],
    stock: 18,
    image: "https://images.pexels.com/photos/27411123/pexels-photo-27411123/free-photo-of-man-in-shirt-sitting-on-chair.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 54,
    category: "jackets",
    name: "Windbreaker",
    description: "Lightweight windbreaker for outdoor activities.",
    price: 49.99,
    colors: ["Green", "Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    image: "https://images.pexels.com/photos/29491846/pexels-photo-29491846/free-photo-of-edgy-fashion-portrait-of-women-on-old-train.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 55,
    category: "shirts",
    name: "Flannel Shirt",
    description: "Cozy flannel shirt for colder weather.",
    price: 34.99,
    colors: ["Red", "Blue", "Green"],
    sizes: ["S", "M", "L"],
    stock: 12,
    image: "https://images.pexels.com/photos/7945660/pexels-photo-7945660.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 56,
    category: "pants",
    name: "Slim Fit Jeans",
    description: "Trendy slim-fit jeans for casual wear.",
    price: 49.99,
    colors: ["Black", "Dark Blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 14,
    image: "https://images.pexels.com/photos/26548170/pexels-photo-26548170/free-photo-of-woman-sitting-on-beach.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 57,
    category: "shoes",
    name: "Casual Sneakers",
    description: "Comfortable sneakers for everyday wear.",
    price: 39.99,
    colors: ["White", "Grey", "Black"],
    sizes: ["7", "8", "9", "10"],
    stock: 20,
    image: "https://images.pexels.com/photos/16013682/pexels-photo-16013682/free-photo-of-shopla.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 58,
    category: "accessories",
    name: "Wool Scarf",
    description: "Soft wool scarf for winter.",
    price: 24.99,
    colors: ["Grey", "Red", "Blue"],
    sizes: ["One Size"],
    stock: 25,
    image: "https://images.pexels.com/photos/18286288/pexels-photo-18286288/free-photo-of-model-posing-in-leather-jacket-and-jeans.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 59,
    category: "shirts",
    name: "Polo Shirt",
    description: "Classic polo shirt for smart casual wear.",
    price: 29.99,
    colors: ["White", "Navy", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 18,
    image: "https://images.pexels.com/photos/27857377/pexels-photo-27857377/free-photo-of-a-man-with-curly-hair-sitting-on-a-couch.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 60,
    category: "pants",
    name: "Jogger Pants",
    description: "Comfortable jogger pants for lounging or workouts.",
    price: 34.99,
    colors: ["Black", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    image: "https://images.pexels.com/photos/16013680/pexels-photo-16013680/free-photo-of-jaido-p-x-fireboy-dml.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 61,
    category: "jackets",
    name: "Puffer Jacket",
    description: "Warm puffer jacket for cold weather.",
    price: 89.99,
    colors: ["Black", "Navy", "Red"],
    sizes: ["M", "L", "XL"],
    stock: 10,
    image: "https://images.pexels.com/photos/29492029/pexels-photo-29492029/free-photo-of-elegant-woman-posing-indoors-with-city-view.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 62,
    category: "dresses",
    name: "Summer Dress",
    description: "A lightweight summer dress with floral prints.",
    price: 45.99,
    colors: ["Yellow", "Pink", "Blue"],
    sizes: ["S", "M", "L"],
    stock: 20,
    image: "https://images.pexels.com/photos/29413594/pexels-photo-29413594/free-photo-of-elegant-pakistani-dress-fashion-portrait-in-lahore.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 63,
    category: "hoodies",
    name: "Pullover Hoodie",
    description: "A cozy pullover hoodie for casual wear.",
    price: 39.99,
    colors: ["Grey", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
    image: "https://images.pexels.com/photos/2373900/pexels-photo-2373900.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 64,
    category: "shorts",
    name: "Denim Shorts",
    description: "Trendy denim shorts for summer days.",
    price: 29.99,
    colors: ["Blue", "Light Blue"],
    sizes: ["S", "M", "L"],
    stock: 18,
    image: "https://images.pexels.com/photos/29466271/pexels-photo-29466271/free-photo-of-stylish-woman-posing-against-modern-urban-architecture.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 65,
    category: "suits",
    name: "Formal Suit",
    description: "Elegant formal suit for business or events.",
    price: 199.99,
    colors: ["Black", "Navy", "Grey"],
    sizes: ["M", "L", "XL"],
    stock: 12,
    image: "https://images.pexels.com/photos/29447409/pexels-photo-29447409/free-photo-of-elegant-woman-in-lavender-floral-gown.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 66,
    category: "dresses",
    name: "Evening Gown",
    description: "A luxurious gown perfect for special occasions.",
    price: 149.99,
    colors: ["Red", "Emerald Green", "Black"],
    sizes: ["S", "M", "L"],
    stock: 10,
    image: "https://images.pexels.com/photos/29477063/pexels-photo-29477063/free-photo-of-elegant-woman-in-blue-dress-by-stone-archway.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 67,
    category: "hoodies",
    name: "Zipper Hoodie",
    description: "A stylish zipper hoodie for everyday wear.",
    price: 44.99,
    colors: ["Blue", "Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 30,
    image: "https://images.pexels.com/photos/3061830/pexels-photo-3061830.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 68,
    category: "shorts",
    name: "Athletic Shorts",
    description: "Breathable shorts for sports and workouts.",
    price: 24.99,
    colors: ["Black", "White", "Grey"],
    sizes: ["S", "M", "L"],
    stock: 25,
    image: "https://images.pexels.com/photos/4945034/pexels-photo-4945034.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 69,
    category: "suits",
    name: "Tuxedo",
    description: "Classic tuxedo for black-tie events.",
    price: 249.99,
    colors: ["Black", "Navy"],
    sizes: ["M", "L", "XL"],
    stock: 8,
    image: "https://images.pexels.com/photos/9849647/pexels-photo-9849647.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 70,
    category: "shirts",
    name: "Cotton Shirt",
    description: "Comfortable cotton shirt for daily wear.",
    price: 27.99,
    colors: ["White", "Light Blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 35,
    image: "https://images.pexels.com/photos/27411114/pexels-photo-27411114/free-photo-of-man-in-shirt-sitting-on-chair.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 71,
    category: "dresses",
    name: "Party Dress",
    description: "Glamorous dress for parties and celebrations.",
    price: 89.99,
    colors: ["Gold", "Silver", "Black"],
    sizes: ["S", "M", "L"],
    stock: 15,
    image: "https://images.pexels.com/photos/7881297/pexels-photo-7881297.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 72,
    category: "pants",
    name: "Wide Leg Pants",
    description: "Fashion-forward wide-leg pants for a chic look.",
    price: 49.99,
    colors: ["Black", "Beige"],
    sizes: ["S", "M", "L"],
    stock: 12,
    image: "https://images.pexels.com/photos/25078946/pexels-photo-25078946/free-photo-of-brunette-woman-sitting-in-white-suit-jacket-and-jeans.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 73,
    category: "jackets",
    name: "Blazer",
    description: "Smart blazer for a professional appearance.",
    price: 79.99,
    colors: ["Navy", "Grey", "Black"],
    sizes: ["M", "L", "XL"],
    stock: 16,
    image: "https://images.pexels.com/photos/2530203/pexels-photo-2530203.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 74,
    category: "hoodies",
    name: "Graphic Hoodie",
    description: "Hoodie with stylish graphic prints.",
    price: 39.99,
    colors: ["White", "Black", "Red"],
    sizes: ["S", "M", "L", "XL"],
    stock: 18,
    image: "https://images.pexels.com/photos/1820658/pexels-photo-1820658.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 75,
    category: "shorts",
    name: "Casual Shorts",
    description: "Lightweight shorts for lounging and casual outings.",
    price: 21.99,
    colors: ["Khaki", "Navy", "Olive"],
    sizes: ["S", "M", "L"],
    stock: 28,
    image: "https://images.pexels.com/photos/1375849/pexels-photo-1375849.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 76,
    category: "dresses",
    name: "Cocktail Dress",
    description: "Elegant cocktail dress for evening parties.",
    price: 99.99,
    colors: ["Black", "Royal Blue", "Burgundy"],
    sizes: ["S", "M", "L"],
    stock: 14,
    image: "https://images.pexels.com/photos/8429050/pexels-photo-8429050.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 77,
    category: "skirts",
    name: "Pleated Skirt",
    description: "Elegant pleated skirt suitable for casual and formal wear.",
    price: 35.99,
    colors: ["Black", "Beige", "Pink"],
    sizes: ["S", "M", "L"],
    stock: 20,
    image: "https://images.pexels.com/photos/1007018/pexels-photo-1007018.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 78,
    category: "scarves",
    name: "Silk Scarf",
    description: "Luxurious silk scarf with floral patterns.",
    price: 24.99,
    colors: ["Red", "Blue", "White"],
    sizes: ["One Size"],
    stock: 30,
    image: "https://images.pexels.com/photos/4728655/pexels-photo-4728655.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 79,
    category: "jumpsuits",
    name: "Casual Jumpsuit",
    description: "Comfortable jumpsuit for relaxed outings.",
    price: 49.99,
    colors: ["Olive Green", "Navy", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 15,
    image: "https://images.pexels.com/photos/13219624/pexels-photo-13219624.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 80,
    category: "vests",
    name: "Puffer Vest",
    description: "Stylish puffer vest for chilly weather.",
    price: 54.99,
    colors: ["Black", "Grey", "Red"],
    sizes: ["S", "M", "L"],
    stock: 25,
    image: "https://images.pexels.com/photos/4484152/pexels-photo-4484152.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 81,
    category: "cardigans",
    name: "Knitted Cardigan",
    description: "Cozy knitted cardigan for a warm, stylish look.",
    price: 39.99,
    colors: ["Cream", "Brown", "Grey"],
    sizes: ["S", "M", "L"],
    stock: 18,
    image: "https://images.pexels.com/photos/5706270/pexels-photo-5706270.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 82,
    category: "skirts",
    name: "Denim Skirt",
    description: "Trendy denim skirt with a frayed hem.",
    price: 29.99,
    colors: ["Blue", "Dark Blue", "Black"],
    sizes: ["S", "M", "L"],
    stock: 22,
    image: "https://images.pexels.com/photos/2820793/pexels-photo-2820793.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 83,
    category: "scarves",
    name: "Woolen Scarf",
    description: "Soft woolen scarf to keep you warm and stylish.",
    price: 19.99,
    colors: ["Grey", "Beige", "Maroon"],
    sizes: ["One Size"],
    stock: 35,
    image: "https://images.pexels.com/photos/8487178/pexels-photo-8487178.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 84,
    category: "jumpsuits",
    name: "Formal Jumpsuit",
    description: "Elegant jumpsuit for office or formal events.",
    price: 74.99,
    colors: ["Black", "Navy", "Emerald Green"],
    sizes: ["S", "M", "L"],
    stock: 10,
    image: "https://images.pexels.com/photos/6344645/pexels-photo-6344645.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 85,
    category: "vests",
    name: "Denim Vest",
    description: "Stylish denim vest for layering.",
    price: 34.99,
    colors: ["Blue", "Light Blue", "Black"],
    sizes: ["S", "M", "L"],
    stock: 20,
    image: "https://images.pexels.com/photos/4940724/pexels-photo-4940724.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 86,
    category: "cardigans",
    name: "Long Cardigan",
    description: "Lightweight long cardigan for everyday use.",
    price: 44.99,
    colors: ["Pink", "Beige", "Black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 12,
    image: "https://images.pexels.com/photos/5638645/pexels-photo-5638645.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 87,
    category: "skirts",
    name: "Wrap Skirt",
    description: "Flattering wrap skirt with tie detail.",
    price: 39.99,
    colors: ["Red", "Black", "White"],
    sizes: ["S", "M", "L"],
    stock: 17,
    image: "https://images.pexels.com/photos/1441025/pexels-photo-1441025.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 88,
    category: "scarves",
    name: "Printed Scarf",
    description: "Lightweight scarf with modern prints.",
    price: 15.99,
    colors: ["Blue", "Yellow", "Pink"],
    sizes: ["One Size"],
    stock: 40,
    image: "https://images.pexels.com/photos/8575366/pexels-photo-8575366.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 89,
    category: "jumpsuits",
    name: "Sleeveless Jumpsuit",
    description: "Casual sleeveless jumpsuit with pockets.",
    price: 42.99,
    colors: ["White", "Olive", "Brown"],
    sizes: ["S", "M", "L"],
    stock: 18,
    image: "https://images.unsplash.com/photo-1519150268069-c094cfc0b3c1?w=600&auto=format&fit=crop&q=60",
  },
  {
    id: 90,
    category: "vests",
    name: "Knitted Vest",
    description: "Trendy knitted vest for layering over shirts.",
    price: 27.99,
    colors: ["Cream", "Brown", "Black"],
    sizes: ["S", "M", "L"],
    stock: 30,
    image: "https://images.pexels.com/photos/8484054/pexels-photo-8484054.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 91,
    category: "cardigans",
    name: "Chunky Cardigan",
    description: "Thick cardigan perfect for colder months.",
    price: 59.99,
    colors: ["Grey", "Green", "Black"],
    sizes: ["S", "M", "L"],
    stock: 14,
    image: "https://images.pexels.com/photos/27700948/pexels-photo-27700948/free-photo-of-fashion-model-sitting-in-by-staircase.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 92,
    category: "skirts",
    name: "Maxi Skirt",
    description: "Flowy maxi skirt for a bohemian look.",
    price: 49.99,
    colors: ["Maroon", "Black", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    stock: 15,
    image: "https://images.unsplash.com/photo-1520970014081-79c8dd86fc73?w=600&auto=format&fit=crop&q=60",
  },
  {
    id: 93,
    category: "scarves",
    name: "Cotton Scarf",
    description: "Soft cotton scarf for everyday use.",
    price: 12.99,
    colors: ["White", "Grey", "Black"],
    sizes: ["One Size"],
    stock: 50,
    image: "https://images.pexels.com/photos/2388245/pexels-photo-2388245.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 94,
    category: "jumpsuits",
    name: "Wide Leg Jumpsuit",
    description: "Fashion-forward wide-leg jumpsuit.",
    price: 68.99,
    colors: ["Teal", "Black", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    stock: 12,
    image: "https://images.pexels.com/photos/2699250/pexels-photo-2699250.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 95,
    category: "vests",
    name: "Faux Fur Vest",
    description: "Elegant faux fur vest for special occasions.",
    price: 79.99,
    colors: ["White", "Black", "Brown"],
    sizes: ["S", "M", "L"],
    stock: 10,
    image: "https://images.pexels.com/photos/8467827/pexels-photo-8467827.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 96,
    category: "cardigans",
    name: "Cropped Cardigan",
    description: "Chic cropped cardigan for modern styling.",
    price: 34.99,
    colors: ["Pink", "Blue", "Grey"],
    sizes: ["S", "M", "L"],
    stock: 25,
    image: "https://images.pexels.com/photos/2480450/pexels-photo-2480450.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 97,
    category: "skirts",
    name: "A-Line Skirt",
    description: "Classic A-line skirt for a sleek and flattering look.",
    price: 29.99,
    colors: ["Black", "Navy", "Grey"],
    sizes: ["S", "M", "L"],
    stock: 20,
    image: "https://images.pexels.com/photos/29466071/pexels-photo-29466071/free-photo-of-chic-woman-walking-in-historic-istanbul-street.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 98,
    category: "scarves",
    name: "Fringed Scarf",
    description: "Stylish fringed scarf with a textured finish.",
    price: 22.99,
    colors: ["Dark Grey", "Beige", "Burgundy"],
    sizes: ["One Size"],
    stock: 30,
    image: "https://images.pexels.com/photos/14592831/pexels-photo-14592831.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 99,
    category: "jumpsuits",
    name: "Boho Jumpsuit",
    description: "Boho-inspired jumpsuit with a relaxed fit and vibrant print.",
    price: 64.99,
    colors: ["Teal", "Purple", "Orange"],
    sizes: ["S", "M", "L"],
    stock: 12,
    image: "https://images.pexels.com/photos/22882064/pexels-photo-22882064/free-photo-of-a-fashionable-woman-holding-a-bunch-of-tulips.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 100,
    category: "cardigans",
    name: "Button-Down Cardigan",
    description: "Cozy button-down cardigan perfect for layering.",
    price: 39.99,
    colors: ["Black", "Charcoal", "Pink"],
    sizes: ["S", "M", "L"],
    stock: 28,
    image: "https://images.pexels.com/photos/3021318/pexels-photo-3021318.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];